name: Setup CI

runs:
  using: composite
  steps:
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: pnpm

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
