name: Setup CI

runs:
  using: composite
  steps:
    - name: Setup Node.js 20.x with pnpm
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml
        package-manager: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
