name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Build package
        run: bun run build
      - name: Check build output
        run: ls -la dist/

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Lint
        run: bun lint
      - name: Type check
        run: bun types:check
      - name: Bun tests
        run: bun test
        env:
          ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
          ZOHO_ORGANIZATION_ID: ${{ secrets.ZOHO_ORGANIZATION_ID }}

  package-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Build
        run: bun run build
      - name: Pack and test package
        run: |
          npm pack
          mkdir test-install
          cd test-install
          bun init -y
          bun add ../smoasters-zoho-suite-*.tgz
          echo "import { ZohoSuite } from '@smoasters/zoho-suite'; console.log('Import works!');" > test.js
          bun run test.js
