name: Release
on:
  push:
    branches:
      - main
      - next
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    if: github.repository == 'coffeeannan/zoho-suite'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Build
        run: bun run build
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          version: bunx changeset version
          publish: bunx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
